### PR TITLE
Config Annotations+Gui and Config-Autosync from Server

### PR DESCRIPTION
**Pull request by MajorTuvok**
Config Annotations+Gui and Config-Autosync from Server.

This switches the Config over to Config Annotations, whilst at the same time remaining compatible with the existing Config Files. This results in the automatic creating of a Config Gui.

The Config functions In-Game as a master copy for the SyncedConfig class, which holds all the config values and automatically syncs them from Server to Client. In order to do this the FieldSerializer class is responsible for converting the Fields values into a syncable Data Format. Because of the TypeMapping performed in the Process it now becomes possible to use any POJO as a synced field in the SyncedConfig class, which can be mapped to a single valid Config Entry. This PR makes use of this to replace the old BlacklistBlocks class with the new PatternList, which can be accessed directly from the SyncedConfig class.

The PatternList class enables the BG-Block-Blacklist to use Regex. as Entries, so that users can define arbitarily complex Patterns of Blocks to Blacklist (and turn this into a whitelist, with little effort).

In the Process this solves #9...
(I remade this in order not to pollute your commit history @Direwolf20-MC )

### CODE REVIEW

**Comment by MajorTuvok** [comment]
There's a bug in github I think: it also shows the changes I pulled in from here!!! (which are obviously already applied)

**Comment by Heufneutje** [comment]
Whenever you try to update your branch with upstream changes, it's generally a better idea to use rebase instead of merge. That makes it so that all the changes you make are placed on top of the upstream commit history rather than the upstream history being merged into it. I'm guessing the merged changes are squashed into your commit now which makes them show up despite already being applied.

**Comment by MajorTuvok** [comment]
Ah thanks @Heufneutje ...
So @Direwolf20-MC, should I recreate it one more time, this time with a rebase, or is this ok as it is...?

**Comment by MichaelHillcox** [comment]
@MajorTuvok I'd suggest closing this PR and reopening it without having merged master in. Either use rebase or don't merge and hope their is no merge conflicts 👍

**Comment by MajorTuvok** [comment]
I'll try (tomorrow or the following day)

**Comment by MajorTuvok** [comment]
Hm, that did not what I expected it to do

**Pull request closed without merging**
