### PR TITLE
Fix UniqueItem not overriding equals and hashcode, whilst at the same time being used as a key in HashMaps

### PR DESCRIPTION
**Pull request by MajorTuvok**
Fix UniqueItem which doesn't override equals and hashcode being used as a Map key. Convert these Map's to Multiset's, as that is what they are actually used for. As an Implementation I always chose HashMultiSet - UniqueItem now correctly overrides equals and hashcode. This should significantly increase Performance, as I also changed the Map Accesses to fallback to the Multisets query Methods instead of iterating over the whole map.

### CODE REVIEW

**Comment by MichaelHillcox** [comment]
@Direwolf20-MC You should likely go ahead and pull this is an it's only fixing an issue with overriding the wrong things. There shouldn't be any functional impact to the mod from this 👍

**Comment by MajorTuvok** [comment]
This is superseded by #189 (I merged that in there), though it is still something that might improve performance and readability in the mean time.

**Comment by Direwolf20-MC** [comment]
@MajorTuvok Due to me pulling in other requests, I made this one have conflicts :( is it an easy thing to fix?

**Comment by MajorTuvok** [comment]
@Direwolf20 can this be merged?

**Pull request merged**
