### PR TITLE
Allow construction blocks to use neighboring block brightness.

### LINKED ISSUE #69: Lighting glitches when copying slabs as construction paste
Construction paste on left, normal slabs on right.

### PR DESCRIPTION
**Pull request by Phylogeny**
Fixes #69

### CODE REVIEW

**Comment by Direwolf20-MC** [comment]
I also did this, which seemed to help quite a bit :) 

https://github.com/Direwolf20-MC/BuildingGadgets/commit/b7a9e5a7869ec59886f5e7983998f619152ac224

**Comment by Phylogeny** [comment]
I've just done some rather rigorous testing, and it appears that b7a9e5a fixes the AO for stairs and slabs (by removing AO that shouldn't be there), while it breaks the AO only for double slabs (by removing AO that should be there).

Given that stairs and slabs are used **far** more often than double slabs, I'd say the change does much more good than harm, and that it's well worth it. :)

**Comment by Direwolf20-MC** [comment]
Cool thank you for testing, I did this quickly between work meetings, and didn't get a chance to exhaustively test all scenarios. I think i'm ok with the ambient occlusion being off with double slabs, because it's barely noticeable.

**Comment by Phylogeny** [comment]
Agreed.

**Pull request merged**
