### PR TITLE
Add more config options - Switch to Config Annotations - Auto sync from server

### PR DESCRIPTION
**Pull request by MajorTuvok**
So what does this do:

Originally I only wanted to add a few more config options (cause for instance the exchanging gadget is in my opinion to op, when farming vast amounts of obsidian)
- Added Black-/Whitelist for Building-/Exchangingmodes
- Added Black-/Whitelist for the Blocks placed by the BuildingGadget
- Added Black-/Whitelist for the Blocks taken (change-Block) and placed (exchange Block) by the ExchangingGadget
- I added the raytrace as a config option (as your todo suggested)
- and I allowed people to disable placing anchors

But me being me, this rapidly got out of hand again - I hate the old config system and therefore swapped to the [new one](https://mcforge.readthedocs.io/en/latest/config/annotations/).
After I did this, I noticed that players might be able get around limitations (like block black-/whitelists) imposed by the server via a different config (I didn' dug deep enough into your code to find out, what is done server-side and what client-side) and so I added the InGameConfig class which is always overridden when the player joins an server.

I know that currently it might be possible to enter an disabled mode if this is the default mode of an new gadget.
I haven't done much other testing than verifying that the server/client sync works like it should.
Will fix that tomorrow...

I hope that this isn't too much and I'd appreciate any feedback...
(I love this mod and hope that this helps you to get the new features you said you were planning in soon)

### CODE REVIEW

**Comment by Direwolf20-MC** [comment]
Thank you for this, a lot of whats here was stuff I planned to do (Once I figured out how to do half of it). This'll save me a bit of that. I plan to use your code as a basis to write it all myself (as my goal is to learn by doing, and I don't learn if i don't do it!) :). VERY MUCH APPRECIATED!

**Comment by MajorTuvok** [comment]
:)
You''re welcome

**Comment by MajorTuvok** [comment]
oh, sry...
didn't want to create such a mess... 
:(
I just wanted to finish it up...

**Comment by Phylogeny** [comment]
Evidently, the EventBusSubscriber annotation should explicitly reference the mod id when on non-@Mod-containing classes:
`@EventBusSubscriber(modid = BuildingGadgets.MODID)`

**Comment by Phylogeny** [comment]
Yeah, I've not personally seen problems arise from leaving it out, but according to the documentation adding it "prevent[s] early classloading of classes not owned by your mod".

**Comment by MajorTuvok** [comment]
Well, now it is corrected...

Though I was unable to find out where the Anchor is set and therefore could no longer implment the allowAnchor config Option.
In addition to that I would have to look deeper into it to find out how to apply Black/Whitelisting of toolModes, cause of the new cycle used to select ToolModes.

I have left them in there, but they don't do anything at the moment...
If you want me to implement them Dire, just say so - Otherwise I'll leave it like that cause you intend to implement it yourself anyway...

**Comment by Phylogeny** [comment]
Might as well fix Dire's missing EventBusSubscriber modid reference in CommonProxy, too. As a reminder to him.

**Comment by Direwolf20-MC** [comment]
Closing this for now because its pretty old and has lots of conflicts of course (Thats on me!) sorry!

**Comment by MichaelHillcox** [comment]
I might go over this one and update it if @MajorTuvok doesn't have time to do it :)

**Comment by MajorTuvok** [comment]
Cause of Uni I really don't have much time...
I intended to take next Thursday as a free programming day (Lectures end on Wednesday already).
I'll see if I get to this, but the Tag System Extension has higher Priority...
If you want to, you can take it over - I don't mind. I'm just to busy to do much more than write a few comments and read what's going on github.

**Pull request closed without merging**
