### PR TITLE
Potentially fix #410

### LINKED ISSUE #410: [1.14.4] Block::getNameTextComponent called on server when it's @OnlyIn(Dist.CLIENT)
* Forge version 28.1.87
* Building Gadgets version 3.1.1b (provided to avoid the crash with another mod)
* *If the issue is a crash*; https://gist.github.com/duely/e8cd942b0a358539b256b5d48487701f
* How to reproduce the issue: The issue appears to happen when attempting to select the lower half of a dark oak door with the exchanging gadget

Based on MCP bot: 

As noted by it being client-side only, I double-checked my locally decompiled source:

```java
   @OnlyIn(Dist.CLIENT)
   public ITextComponent getNameTextComponent() {
      return new TranslationTextComponent(this.getTranslationKey());
   }```

I'm not sure why it's being called on the server in this case, but definitely something to consider.

### PR DESCRIPTION
**Pull request by noobanidus**
As Block::getNameTextComponent is annotated as `@OnlyIn(Dist.CLIENT)`, instead of calling that, just do what it does: create a new TranslationTextComponent using the block's translation key.

### CODE REVIEW

**Comment by duely** [comment]
I'm pretty sure the only other usage of this was in LangUtils and specifically inside of a client-specific function. I'll double check.

**Comment by duely** [comment]
Hm, that could actually be problematic (I haven't looked at the usages of LangUtils in general), so I've adjusted it as well.

**Comment by MichaelHillcox** [comment]
I wouldn't go to far. I'm going to be completely redoing the 1.14 port.

**Comment by duely** [comment]
I think I've covered it, there's only two instances where it's used and both of them can easily be changed to `new TranslationTextComponent(block.getTranslationKey())`.

**Pull request merged**
