### PR TITLE
Soft coded Registry Names as parameters

### PR DESCRIPTION
**Pull request by TuxMan20**
Make it easier to further expand the tools and avoid Registry names conflicts

### CODE REVIEW

**Comment by MajorTuvok** [comment]
These Names should be moved to reference anyway...

**Comment by MichaelHillcox** [comment]
Hmm, this is actually all changed in our 1.13.2 branch so I'm not sure if this is viable for us to merge in as it conflicts heavily with the new systems implemented as we've built a complete registry system.

**Comment by MajorTuvok** [comment]
Why 10000 commits?

**Comment by MajorTuvok** [comment]
I literally just wanted to create a review stating exactly that @MichaelHillcox... XD

**Comment by MichaelHillcox** [comment]
So I'm going to go ahead and close this PR. Not that it isn't a worth while merge, it's purely as the changes have already been made on a different branch of the repo. Please feel free to have a peak at our todo list issue and our 1.13.x branch to see if any improvements can be made on that end.

Thank you again for taking the time and contributing.

**Comment by Phylogeny** [comment]
The replacement of strings peppered throughout the mod with constants in a central set of reference classes in their own sub-pakacge (of `utils/ref/` in 1.13) needs to be done anyway. The changes here will be superseded by that, whenever it gets done.

**Comment by TuxMan20** [comment]
Glad to know you guys had already caught that ! :D 
Any ETA of seeing it in the 1.12 branch?

**Comment by Phylogeny** [comment]
And breaking a change so small and simple as this into multiple commits is bad form. As is reusing vague commit messages, like that. All the changes here should have been in the first commit.

**Comment by MichaelHillcox** [comment]
We're unlikely to port the code back to 1.12 as there is a lot of heavy changes.

**Comment by TuxMan20** [comment]
@Phylogeny All right! Will make sure to better format them next time.

**Comment by MajorTuvok** [comment]
As to an ETA, I wanted to do a more Reference work tomorrow evening, before going over to API Docs...

**Pull request closed without merging**
