### PR TITLE
changed paste container variants to use polymorphism

### PR DESCRIPTION
**Pull request by hnOsmium0001**
removed unnecessary separate classes for tier 1, 2, and 3 construction paste containers.

This is not in a separate branch since there will be no more appending pull requests.

### CODE REVIEW

**Comment by Phylogeny** [comment]
Why is this change not included in #222?

**Comment by hnOsmium0001** [comment]
I tried to follow the "minimum pull request" idea, maybe this is a bad idea.

I will close that pull request and then merge the branches locally to this pull request.

**Comment by Phylogeny** [comment]
Why not just add this change to the preexisting PR?

**Comment by hnOsmium0001** [comment]
sorry for that, this is my first time making a official pull request

**Comment by hnOsmium0001** [comment]
See #222

**Pull request closed without merging**
