### PR TITLE
Merge current 1.13 port status.

### PR DESCRIPTION
**Pull request by Phylogeny**
This supersedes #235

### CODE REVIEW

**Comment by MichaelHillcox** [comment]
I'm happy to have this merged in if @MajorTuvok is too

**Comment by MajorTuvok** [comment]
Me too, though I hope github doesn't complain because I haven't pushed yet

**Comment by MajorTuvok** [comment]
Give me a moment, to push what I've got as not fully running registration, and then merge?

**Comment by Phylogeny** [comment]
Yeah, just push what you have; then after the merge, we can continue here.

**Pull request merged**
