### PR TITLE
V2 Added a new mode for building gadget - brush mode

### PR DESCRIPTION
**Pull request by CyprinusCarpio**
I have created a new mode for building gadget that makes a sphere of given radius (uses range of gadget as radius).
https://imgur.com/a/VHJXNpT

### CODE REVIEW

**Comment by MajorTuvok** [comment]
If you can create a sphere with it, could you add a circle too, if you're at it...?

**Comment by CyprinusCarpio** [comment]
That definitely wouldn't be INSANELY hard.. i think that would just be removing the for loop that loops the Y axis? I'll give it a try later.

**Comment by CyprinusCarpio** [comment]
Thats actually the first thing i coded for Minecraft (in Java), and my vastly superior knowledge of C++(to that of Java, which is basically null) tells me that the 8 lines containing "new BlockPos" could lead to memory fuckup-age, because i dynamically allocate 8 BlockPos'es on every block, instead of 1 in the rest of modes.. This definitely has some performance impact.

**Comment by Direwolf20-MC** [comment]
Hrmm. I appreciate the effort, but not sure it fits what I'm looking for the mod to do right now. Perhaps I should add an API or something if people want to add their own modes. For now closing this, thank you anyway though!

**Comment by MajorTuvok** [comment]
I know that this isn't applicable for your 'creating 8*range^3 BlockPos objects' 'problem', but there is a mutable BlockPos class...

And which loop would become obsolete would actually depend on the Block-Face the User is looking at (@see Build-to-me mode, if I recall correctly)

**Pull request closed without merging**
