### PR TITLE
Initial port of GUI and keybinding functionality.

### PR DESCRIPTION
**Pull request by Phylogeny**
Most GUIs don't do much yet, but they open. Keybindings seem to work fine.

### CODE REVIEW

**Comment by MajorTuvok** [comment]
I think you can merge in directly, as we aren't in a state yet, where things are expected to work. So if there is some error in it, it isn't super important...?

**Comment by MajorTuvok** [comment]
(Also I won't have any time til tomorrow evening again...)

**Comment by Phylogeny** [comment]
Ok. I just wanted to make a quick PR in case anyone had mediate objections or concerns.

**Comment by MichaelHillcox** [comment]
All looking great!

**Pull request merged**
