### PR TITLE
Fixed template rotation

### LINKED ISSUE #478: Stairs rotate incorrectly via the Copy Paste Gadget
Forge version: 31.1.89
Building Gadgets version: 3.3.5

Hey, I installed the latest version of the mod into my 1.15.2 modpack and encountered an issue. Whenever I **Rotate** builds with the Copy Paste Gadget, the entire build rotates counter-clockwise, with the exception of stairs: they rotate clockwise.

image

As you can see, I built and copied a little compass to test this (blocks rotated north -> west; stairs rotated north -> east). I tested with Vanilla stairs and they do the same thing. 

I would like to copy builds from my Creative worlds into Survival and use Building Gadgets for that, any ideas what might be causing this?

### PR DESCRIPTION
**Pull request by hvdklauw**
Fixed rotating a template to use the wrong calculation for the rotation matrix causing the blocks to be placed incorrectly.

Fixes #478

### CODE REVIEW

**Comment by MichaelHillcox** [comment]
I have a feeling Rx and Rz are also wrong on their [1][2] & [2][1] (X) and [0][1] & [1][0] (Z). I've compaired our code to the logic you presented in wiki page. Could you confirm this before I merge and maybe test if you're able to?

**Comment by hvdklauw** [comment]
Ah yes, you are right ! They are wrong way around too...

or the matrixMul is wrong and the rotationMatrixFor was right... depends on how you define the one or the other :joy:

**Comment by hvdklauw** [comment]
Ok, fixed those too and fixed the commit message, some vim shenanigans

**Comment by MichaelHillcox** [comment]
Have you been able to test your changes?

**Comment by hvdklauw** [comment]
Yes and no, as these functions (rotateMatrix and matrixMul) are only used in the Template class for rotating around the Y axis
That is what I tested, after your remark I manually checked the X and Z ones based on the wiki articles and changed those too to at least use the same dimentional directionality as the Y axis.

**Comment by MichaelHillcox** [comment]
I'll pull and test myself, thanks for your work. I'll review this soon

**Pull request merged**
