### PR TITLE
Automatically draw GUI background that is any size

### PR DESCRIPTION
**Pull request by hnOsmium0001**
Usually what people do for GUI backgrounds is they put it in a .png file, and draw it as a texture. However since Minecraft limits texture size to 256*256, this cannot handle backgrounds bigger, and this strategy is very inflexible.

## Additions

This PR only adds 1 class, `Background` (not a very descriptive name, might have to be changed), and it has 1 public method that draws a vanilla styled background at the given position. The size will include the borders, which means both width and height must be higher than 8 (border is 4 pixels wide). Additionally a texture is included to store the base border texture

### Corner Pieces
Corner pieces have a fixed size, therefore they are drawn directly, with no transformations, from the texture file at the appropriate location.

### Edge Pieces
Edge pieces' have variable length, and each slice looks exactly the same. The strategy I used is to use a pre-made 3 pixel wide sample, in each orientation, and stretch them using fixed UV coordinates (vertexes used for drawing may vary)

### Body Pieces
Body pieces can have any size, but it is pure in color (`0xC6C6C6`). Therefore a colored quad is good enough for the whole body piece. Note that there is a sample body piece in the texture file, just to indicate that there is a body piece in GUIs.

### GPU Burdens
Drawing GUI using this method will use 9 quads (18 triangles) and 2 drawing passes. Although this is significantly more triangles than using just a texture, modern GPU can handle them like nothing nothing.

## TODOs

This PR does not add any feature or change any logic at all, but the plan is to use this for `DestructionGUI`, `CopyPasteGUI` (note that this should be called `CopyGUI`), `PasteGUI`, and the future `MaterialListGUI` that is being worked on.

### CODE REVIEW

**Comment by MichaelHillcox** [comment]
This seems like overkill. Can you find any instances where a system like this is actually required in the world of modding? any mods that implement a system that isn't using the stock mc method?

**Comment by KingLemming** [comment]
Your initial statement is straight up incorrect. Minecraft can handle files larger than 256x256. Many mods already do this for backgrounds.

Trust me, I'm one of them.

Having said that, this isn't the worst idea but it also just doesn't seem necessary.

**Comment by Phylogeny** [comment]
Not only are there the `GuiUtils#drawContinuousTexturedBox` methods (which tile the background), but here's code I've already added into the mod that draws a textured rect of any size (by just using 1s and 0s for the u/v values): 
https://github.com/Direwolf20-MC/BuildingGadgets/blob/master/src/main/java/com/direwolf20/buildinggadgets/client/gui/GuiButtonIcon.java#L68-L77

I agree that this PR is unnecessary.

**Comment by MichaelHillcox** [comment]
Closing due to the above reasons from @KingLemming and @Phylogeny as well as myself.

**Pull request closed without merging**
